name: Build index.json

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: Install Blender
        uses: bradyajohnston/setup-blender@v3
        with:
          version: "4.4"  # temporarily using 4.4 because 4.5 is down

      - name: build index.json
        run: |
          blender --command extension server-generate --repo-dir=./

      - name: Commit and push build artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.json 
          git commit -m "Update build and index.json" || echo "No changes to commit"
          git push origin HEAD:main
